name = "Weapons Balance - NIArms (New)";
author = "johnb43";
tooltip = "Weapons Balance - NIArms (New)";
tooltipOwned = "Weapons Balance - NIArms (New)";
hideName = 0;
hidePicture = 0;
dir = "@wb_niarms";
actionName = "Github";
action = "https://github.com/johnb432/Weapons-Balance-NIArms";
description = "A collection of balancing mods made by johnb43.";
overview = "A collection of balancing mods made by johnb43.";
picture = "\z\wb_niarms\addons\main\ui\logo_weapons_balance.paa"; // http://getdrawings.com/get-drawing#gun-drawing-in-pencil-27.jpg, http://getdrawings.com/get-drawing#gun-drawing-in-pencil-17.png
logo = "\z\wb_niarms\addons\main\ui\logo_weapons_balance.paa";
logoOver = "\z\wb_niarms\addons\main\ui\logo_weapons_balance.paa";
logoSmall = "\z\wb_niarms\addons\main\ui\logo_weapons_balance.paa";
overviewPicture = "\z\wb_niarms\addons\main\ui\logo_weapons_balance.paa";
